name: Golang Algorithm Club
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
  pre-commit:
    name: pre-commit action
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
      - uses: pre-commit/action@v2.0.2
      - name: Install pre-commit dependencies
        run: |
          go get github.com/fzipp/gocyclo
          go get golang.org/x/tools/cmd/goimports
          go get github.com/go-critic/go-critic/cmd/gocritic
          go get golang.org/x/lint/golint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
