name: Golang Algorithm Club

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
  pre-commit:
    name: pre-commit action
    runs-on: ubuntu-latest
    steps:
      - name: Install pre-commit dependencies
        run: |
          GO111MODULE=off go get github.com/fzipp/gocyclo
          GO111MODULE=off go get golang.org/x/tools/cmd/goimports
          GO111MODULE=off go get -v -u github.com/go-critic/go-critic/cmd/gocritic
          GO111MODULE=off go get -u golang.org/x/lint/golint
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...